version: "3"
services:
  x-ui:
    container_name: x-ui
    image: enwaiax/x-ui # ghcr.io/mhsanaei/3x-ui:latest
    ports:
      - "54321:54321"  # "54321:2053"
      - "80:80/tcp"
      - "80:80/udp"
      - "10000:10000/tcp"
      - "10000:10000/udp"
      - "10001:10001/tcp"
      - "10001:10001/udp"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    restart: unless-stopped
