version: "3"
services:
  x-ui:
    container_name: x-ui
    image: enwaiax/x-ui
    ports:
      - "54321:54321"
      - "80:80/tcp"
      - "80:80/udp"
      - "10000:10000/tcp"
      - "10000:10000/udp"
    dns:
      - "192.168.1.210"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    restart: always
